
version: '3.5'

services:

  redis:
    image: redis
    container_name: redis

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - "60000:27017"
    volumes:
      - mongos:/data/db

  webserver:
    container_name: webserver
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - myapp1
      - myapp2
      - myapp3

  subscriptionServer:
    build:
      context: ./subscriptionServer
      dockerfile: Dockerfile
    image: node-subscription
    container_name: subscriptionServer
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis
      - REDIS_PORT=6379
    command: node subscriptionServer.js

  myapp1:
    build:
      context: ./transactionServer
      dockerfile: Dockerfile
    image: node-app
    container_name: myapp1
    environment:
      - PORT=3001
      - MONGODB_CONNSTRING=mongodb://mongos:27017/seng468db
      - REDIS_ADDR=redis
      - REDIS_PORT=6379
      - QUOTESERVER_ADDR=10.0.0.46
      - QUOTESERVER_PORT=4444
    depends_on:
      - mongos
      - subscriptionServer
    command: ./wait-for.sh mongos:27017 -- npm start
    volumes:
      - node_modules:/usr/local/app/node_modules

  myapp2:
    build:
      context: ./transactionServer
      dockerfile: Dockerfile
    image: node-app
    container_name: myapp2
    environment:
      - PORT=3002
      - MONGODB_CONNSTRING=mongodb://mongos:27017/seng468db
      - REDIS_ADDR=redis
      - REDIS_PORT=6379
      - QUOTESERVER_ADDR=10.0.0.46
      - QUOTESERVER_PORT=4444
    depends_on:
      - mongos
      - subscriptionServer
    command: ./wait-for.sh mongos:27017 -- npm start
    volumes:
      - node_modules:/usr/local/app/node_modules

  myapp3:
    build:
      context: ./transactionServer
      dockerfile: Dockerfile
    image: node-app
    container_name: myapp3
    environment:
      - PORT=3003
      - MONGODB_CONNSTRING=mongodb://mongos:27017/seng468db
      - REDIS_ADDR=redis
      - REDIS_PORT=6379
      - QUOTESERVER_ADDR=10.0.0.46
      - QUOTESERVER_PORT=4444
    depends_on:
      - mongos
      - subscriptionServer
    command: ./wait-for.sh mongos:27017 -- npm start
    volumes:
      - node_modules:/usr/local/app/node_modules

volumes:
  mongos:
  node_modules:

networks:
  default:
    name: seng468
    external: true