
version: '3.4'

services:

  redis:
    container_name: redis
    image: redis

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017

  webserver:
    container_name: webserver
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - myapp1
      - myapp2

  subscriptionServer:
    build:
      context: ./subscriptionServer
      dockerfile: Dockerfile
    image: node-subscription
    container_name: subscriptionServer
    depends_on:
      - redis
    command: ./wait-for.sh redis:6379 -- node subscriptionServer.js

  myapp1:
    build:
      context: ./transactionServer
      dockerfile: Dockerfile
    image: node-app
    container_name: myapp1
    environment:
      - PORT=3001
      - MONGODB_CONNSTRING=mongodb://mongos:27017/seng468db
    depends_on:
      - mongos
      - subscriptionServer
    command: ./wait-for.sh mongos:27017 -- npm start

  myapp2:
    build:
      context: ./transactionServer
      dockerfile: Dockerfile
    image: node-app
    container_name: myapp2
    environment:
      - PORT=3002
      - MONGODB_CONNSTRING=mongodb://mongos:27017/seng468db
    depends_on:
      - mongos
      - subscriptionServer
    command: ./wait-for.sh mongos:27017 -- npm start

networks:
  default:
    name: seng468
    external: true