version: '3.4'

services:

  cfgsvr1:
    container_name: cfgsvr1
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:
      - cfgsvr1:/data/db
    networks:
      seng468:
        ipv4_address: 172.20.0.21

  cfgsvr2:
    container_name: cfgsvr2
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - cfgsvr2:/data/db
    networks:
      seng468:
        ipv4_address: 172.20.0.22

  shard1svr1:
    container_name: shard1svr1
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    volumes:
      - shard1svr1:/data/db
    networks:
      seng468:
        ipv4_address: 172.20.0.23

  shard1svr2:
    container_name: shard1svr2
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    volumes:
      - shard1svr2:/data/db
    networks:
      seng468:
        ipv4_address: 172.20.0.24

  shard2svr1:
    container_name: shard2svr1
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50004:27017
    volumes:
      - shard2svr1:/data/db
    networks:
      seng468:
        ipv4_address: 172.20.0.25

  shard2svr2:
    container_name: shard2svr2
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50005:27017
    volumes:
      - shard2svr2:/data/db
    networks:
      seng468:
        ipv4_address: 172.20.0.26

volumes:
  cfgsvr1: {}
  cfgsvr2: {}
  shard1svr1: {}
  shard1svr2: {}
  shard2svr1: {}
  shard2svr2: {}

networks:
  seng468:
    external: true